const products = [
  {id:'salt-gel',name:'Attapulgite Salt Gel Grade',code:'SG',type:'Drilling Grade',categories:['drilling','industrial'],desc:'High-viscosity attapulgite for salt gel applications in demanding saline, high-pressure and high-heat environments.',tags:['35 cps min.','8% moisture max.'],specs:[['Viscosity at 600 rpm','35 cps minimum'],['Residue above 75 μm','4% maximum'],['Moisture','8% maximum']],apps:['Oil & water drilling','Petrochemicals','Construction chemicals','Powder granulation','Laundry powder']},
  {id:'api-13a',name:'API-13A Section 12',code:'A13',type:'Drilling Grade',categories:['drilling'],desc:'A drilling-grade mineral developed to meet API 13A Section 12 physical parameters for saline drilling conditions.',tags:['API parameters','30 cps min.'],specs:[['Viscosity at 600 rpm','30 cps minimum'],['Residue above 75 μm','8% maximum'],['Moisture','16% maximum']],apps:['Oil-well drilling mud','Water drilling','Petrochemicals','Construction chemicals']},
  {id:'natural-powder',name:'Natural Attapulgite Powder',code:'NP',type:'Natural Grade',categories:['natural','industrial'],desc:'A non-swelling, porous natural powder with high absorbency, suspension performance and binding ability.',tags:['pH 7.6','SG 2.39'],specs:[['Moisture','8–12% | Result: 10.4%'],['Form / colour','Powder / Off white'],['pH','6.5–8.5 | Result: 7.6'],['Specific gravity','2.3–2.4 | Result: 2.39'],['Al₂O₃ / Fe₂O₃','6.2% / 4.6%'],['SiO₂ / CaO / MgO','40.2% / 4.8% / 8.42%'],['LOI','20–25% | Result: 24.2%']],apps:['Industrial absorbents','Animal litter','Pesticide & fertiliser carrier','Drilling fluids','Agricultural chemicals']},
  {id:'flux-fine',name:'Flux Fine −200',code:'F200',type:'Foundry Grade',categories:['industrial'],desc:'Consistent, fine attapulgite powder offering excellent binding and thermal stability for foundry formulations.',tags:['200 mesh','FSV 12–14 ml'],specs:[['Moisture','8–12%'],['Form / colour','Powder / Off white'],['pH','6.5–8.5'],['Swelling index — 1 hr','95 ml minimum'],['Swelling index — 24 hrs','85 ml minimum'],['Particle size 200 mesh (wet)','98% max.'],['FSV','12–14 ml'],['Al₂O₃ / Fe₂O₃','5–10% / 4–5%'],['SiO₂ / CaO / MgO','36–42% / 4–5% / 8–12%'],['LOI','20–25%']],apps:['Foundry blending','Pharmaceutical thickener','Abrasive suspending agent','Wax emulsion stabiliser','Metal drawing lubricants','Construction chemicals','Fertiliser']},
  {id:'premium-325',name:'Premium 325',code:'P325',type:'Premium Grade',categories:['industrial'],desc:'A premium fine powder delivering excellent thickening, suspending and rheological performance across formulations.',tags:['325 mesh','1200–1600 cP'],specs:[['Moisture','6–8%'],['Form / colour','Powder / Off white'],['pH (2% in water)','7–9'],['Surface area (BET)','210 m²/g ±10%'],['Specific gravity','2.3–2.4'],['325 mesh (wet)','98.5% max.'],['Bulk density','0.3–0.4 g/ml'],['Brookfield viscosity','1200–1600 cP (7% water, 50 rpm)'],['Oil absorption','100 ml/100 g'],['Al₂O₃ / Fe₂O₃','5–10% / 4–5%'],['SiO₂ / CaO / MgO','36–42% / 4–5% / 8–12%'],['LOI','20–25%']],apps:['Paints & coatings','Fertilisers','Ceramics','Construction chemicals','Admixtures & sealants','Adhesives','Liquid suspensions','Detergents']},
  {id:'granules',name:'Natural Granules 1–5 mm',code:'NG',type:'Natural Grade',categories:['natural'],desc:'Low-dust, non-swelling porous granules with strong liquid absorption for carriers, litter and industrial use.',tags:['1–5 mm','5.6% moisture'],specs:[['Moisture','5–10% | Result: 5.6%'],['Form','Ball granules, 1–5 mm'],['Colour','Off white'],['pH','6.5–8.5 | Result: 7.6'],['Specific gravity','2.3–2.4 | Result: 2.46'],['Under / oversize','5% | Result: 2.6%'],['Al₂O₃ / Fe₂O₃','6.2% / 4.6%'],['SiO₂ / CaO / MgO','40.2% / 4.8% / 8.42%'],['LOI','20–25% | Result: 24.2%']],apps:['Cat litter','Industrial absorbents','Pesticide carrier','Fertiliser carrier']}
];

const grid=document.querySelector('#productGrid');
if(grid) grid.innerHTML=products.map((p,i)=>`<article class="product-card reveal" data-categories="${p.categories.join(' ')}"><div class="product-photo product-photo-${i+1}"><img src="assets/product-range.jpeg" alt="${p.name}" loading="lazy"></div><div class="product-content"><div class="product-top"><span class="product-num">0${i+1}</span><span class="product-type">${p.type.toUpperCase()}</span></div><div class="product-symbol">${p.code}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="product-meta">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div><button class="details-btn" data-id="${p.id}">View specifications <span>↗</span></button></article>`).join('');

document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;document.querySelectorAll('.product-card').forEach(c=>c.classList.toggle('hide',f!=='all'&&!c.dataset.categories.includes(f)))}));

const modal=document.querySelector('#productModal'), modalContent=document.querySelector('#modalContent');
if(grid&&modal){grid.addEventListener('click',e=>{const btn=e.target.closest('.details-btn');if(!btn)return;const p=products.find(x=>x.id===btn.dataset.id);modalContent.innerHTML=`<div class="modal-body"><span class="section-number">${p.type.toUpperCase()} / PRODUCT DATA</span><h2 id="modalTitle">${p.name}</h2><p class="modal-subtitle">${p.desc}</p><table class="spec-table"><thead><tr><th>Parameter</th><th>Requirement / Result</th></tr></thead><tbody>${p.specs.map(s=>`<tr><td>${s[0]}</td><td><strong>${s[1]}</strong></td></tr>`).join('')}</tbody></table><h3>Typical applications</h3><div class="modal-apps">${p.apps.map(a=>`<span>${a}</span>`).join('')}</div><div class="modal-note"><span>Composition: Hydrated aluminium magnesium silicate</span><strong>25 kg HDPE liner bag</strong></div></div>`;modal.showModal();document.body.classList.add('modal-open')});
function closeModal(){modal.close();document.body.classList.remove('modal-open')}document.querySelector('.modal-close').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()})}

const menu=document.querySelector('.menu-btn'),nav=document.querySelector('.nav-links');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
